package com.okensun.todayfeed.components.feed.domain

import com.okensun.todayfeed.components.articles.api.Article
import com.okensun.todayfeed.components.articles.api.ArticleRepository
import com.okensun.todayfeed.components.weather.api.Weather
import com.okensun.todayfeed.components.weather.api.WeatherRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import java.time.Instant

/**
 * Hand written, not generated by a mocking library. The interfaces are small and were
 * designed for this, so a fake is a few lines and reads as a value rather than as a list of
 * call expectations. See DECISIONS.md.
 */
class FakeArticleRepository(
    articles: List<Article> = emptyList(),
) : ArticleRepository {
    private val feed = MutableStateFlow(articles)

    override fun observeFeed(): Flow<List<Article>> = feed

    override fun observeSaved(): Flow<List<Article>> = feed

    override suspend fun article(id: String): Article? = feed.value.firstOrNull { it.id == id }

    fun emit(articles: List<Article>) {
        feed.value = articles
    }
}

class FakeWeatherRepository(
    weather: Weather? = null,
) : WeatherRepository {
    private val current = MutableStateFlow(weather)

    override fun observeCurrent(): Flow<Weather?> = current

    fun emit(weather: Weather?) {
        current.value = weather
    }
}

fun article(id: String) =
    Article(
        id = id,
        title = "Article $id",
        summary = "Summary $id",
        source = "Spaceflight News",
        imageUrl = null,
        publishedAt = Instant.EPOCH
    )

fun weather() =
    Weather(
        placeName = "Taipei",
        temperatureCelsius = 30.0,
        condition = "Cloudy",
        highCelsius = 31.0,
        lowCelsius = 26.0
    )
