package com.okensun.todayfeed.components.articles.data

import androidx.paging.PagingSource
import androidx.room.Dao
import androidx.room.Query
import androidx.room.Upsert

@Dao
internal interface ArticlesDao {
    /**
     * Generated by room-paging. Paging works out the windows; this only states the order.
     *
     * The id breaks ties. Paging reads windows with `LIMIT` and `OFFSET`, so two rows sharing a
     * published time could otherwise swap places between two queries and be shown twice or
     * skipped at a page boundary. Ties are not hypothetical: an article whose date will not parse
     * is stored at the epoch, and every one of those ties with every other.
     */
    @Query("SELECT * FROM articles ORDER BY publishedAt DESC, id DESC")
    fun pagedArticles(): PagingSource<Int, ArticleEntity>

    @Query("SELECT * FROM articles WHERE id = :id")
    suspend fun findArticle(id: String): ArticleEntity?

    /** How many of these are already stored. This is what tells a refresh it has reached back far enough. */
    @Query("SELECT COUNT(*) FROM articles WHERE id IN (:ids)")
    suspend fun countStored(ids: List<String>): Int

    @Upsert
    suspend fun upsertArticles(articles: List<ArticleEntity>)

    @Query("SELECT * FROM feed_metadata WHERE id = 0")
    suspend fun findMetadata(): FeedMetadataEntity?

    @Upsert
    suspend fun upsertMetadata(metadata: FeedMetadataEntity)

    /**
     * Only where the next page starts and whether there is one. An append must not write the
     * whole row back, because the freshness stamp it read is older than its own request.
     */
    @Query("UPDATE feed_metadata SET nextOffset = :nextOffset, hasMore = :hasMore WHERE id = 0")
    suspend fun setPagingProgress(
        nextOffset: Int,
        hasMore: Boolean,
    )
}
