package com.okensun.todayfeed.components.articles.data

import androidx.paging.PagingSource
import androidx.room.Dao
import androidx.room.Query
import androidx.room.Upsert

@Dao
internal interface ArticlesDao {
    /** Generated by room-paging. Paging works out the windows; this only states the order. */
    @Query("SELECT * FROM articles ORDER BY publishedAt DESC")
    fun pagedArticles(): PagingSource<Int, ArticleEntity>

    @Query("SELECT * FROM articles WHERE id = :id")
    suspend fun article(id: String): ArticleEntity?

    /** How many of these are already stored. This is what tells a refresh it has reached back far enough. */
    @Query("SELECT COUNT(*) FROM articles WHERE id IN (:ids)")
    suspend fun countStored(ids: List<String>): Int

    @Upsert
    suspend fun upsertArticles(articles: List<ArticleEntity>)

    @Query("SELECT * FROM feed_metadata WHERE id = 0")
    suspend fun metadata(): FeedMetadataEntity?

    @Upsert
    suspend fun upsertMetadata(metadata: FeedMetadataEntity)
}
